SystemOrganization addCategory: #'FogBugz-Client'!
SystemOrganization addCategory: 'FogBugz-Client-Announcements'!
SystemOrganization addCategory: 'FogBugz-Client-Core'!
SystemOrganization addCategory: 'FogBugz-Client-Dialog'!
SystemOrganization addCategory: 'FogBugz-Client-Examples'!
SystemOrganization addCategory: 'FogBugz-Client-Network'!
SystemOrganization addCategory: 'FogBugz-Client-Settings'!
