SystemOrganization addCategory: #'FogBugz-Client'!
SystemOrganization addCategory: 'FogBugz-Client-Announcements'!
SystemOrganization addCategory: 'FogBugz-Client-Dialog'!
SystemOrganization addCategory: 'FogBugz-Client-Examples'!
SystemOrganization addCategory: 'FogBugz-Client-Model'!
SystemOrganization addCategory: 'FogBugz-Client-Network'!
SystemOrganization addCategory: 'FogBugz-Client-Settings'!
SystemOrganization addCategory: 'FogBugz-Client-Trait'!
